apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-discovery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "discovery-server"

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: "backend"