apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: redis-dev
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: platform

  sources:
    # Helm Chart Repository
    - repoURL: https://github.com/VaibhavShejul09/centralized-helm-repo.git
      targetRevision: main
      path: charts/redis

      helm:
        valueFiles:
          - $values/environments/dev/cache/redis-values.yaml

    # Values Repository
    - repoURL: https://github.com/VaibhavShejul09/rankx-environments.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true