apiVersion: v1
kind: ResourceQuota
metadata:
  name: qa-quota
  namespace: qa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    pods: "30"
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 10Gi