kind: Deployment
name: discovery-server

replicaCount: 1
syncWave: 1

labels:
  component: discovery
  env: dev
  team: platform
  tier: infra

  owner: platform-team
  criticality: high
  costCenter: engineering
  businessUnit: rankx

  compliance: internal
  dataClassification: internal

  monitoring: enabled
  backup: required

image:
  repository: shejulv088/final_discovery_server
  tag: "2-02b46d8"

service:
  type: ClusterIP
  port: 8761

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  

  container:
    runAsNonRoot: true
    runAsUser: 1001
    privileged: false
    allowPrivilegeEscalation: false   

config: false
secret: false

# -------------------------
# Startup Probe  # startupProbe handles startup delay
# -------------------------
startupProbe:
  path: /actuator/health
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 30   # 150 sec startup time

# -------------------------
# Liveness Probe
# -------------------------
livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10   # 🔥 reduce
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 5

# -------------------------
# Readiness Probe
# -------------------------
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 5    # 🔥 reduce
  periodSeconds: 10         # 🔥 faster response
  timeoutSeconds: 2
  failureThreshold: 3

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"