name: api-gateway
replicaCount: 1
syncWave: 5
kind: Deployment

labels:
  component: gateway
  env: dev
  team: backend
  tier: edge

  owner: platform-team
  criticality: high
  costCenter: engineering
  businessUnit: rankx

  compliance: internal
  dataClassification: internal

  monitoring: enabled
  backup: required

image:
  repository: shejulv088/rankx-apigatway
  tag: "v1"

service:
  type: ClusterIP
  port: 8080
  
securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  

  container:
    runAsNonRoot: true
    runAsUser: 1001
    privileged: false
    allowPrivilegeEscalation: false 



# -------------------------
# Startup Probe  # startupProbe handles startup delay
# -------------------------
startupProbe:
  path: /actuator/health
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 30   # 150 sec startup time

# -------------------------
# Liveness Probe
# -------------------------
livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10   # 🔥 reduce
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 5

# -------------------------
# Readiness Probe
# -------------------------
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 5    # 🔥 reduce
  periodSeconds: 10         # 🔥 faster response
  timeoutSeconds: 2
  failureThreshold: 3

config:
  SPRING_CONFIG_URI: http://config-server:8888
  SPRING_PROFILES_ACTIVE: native
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
  JAVA_TOOL_OPTIONS: "-Xms256m -Xmx350m"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
