namespace: dev

policies:
  defaultDenyIngress: true

#######################################################
frontend:
  enabled: true
#######################################################
frontendadmin:
  enabled: true  
#######################################################
gateway:
  enabled: true
  port: 8080
#######################################################
services:
  config:
    enabled: true
    port: 8888

  discovery:
    enabled: true
    port: 8761

  auth:
    enabled: true
    port: 8081

  problem:
    enabled: true
    port: 8082

  submission:
    enabled: true
    port: 8083

  quize:
    enabled: true
    port: 8086

  user:
    enabled: true
    port: 8088  

  result:
    enabled: true
    port: 8087    

  question:
    enabled: true
    port: 8085

  attempt:
    enabled: true
    port: 8084       
######################################################
redis:
  enabled: true
  port: 6379

#######################################################
database:

  auth:
    enabled: true
    port: 3306


  problem:
    enabled: true
    port: 3306   
    
  submission:
    enabled: true
    port: 3306  

  attempt:
    enabled: true
    port: 3306 

  question:
    enabled: true
    port: 3306

  quize:
    enabled: true
    port: 3306 

  result:
    enabled: true
    port: 3306 

  user:
    enabled: true
    port: 3306          