kind: Deployment

name: config-server

replicaCount: 1
syncWave: 0

labels:
  component: backend
  env: dev
  team: backend
  tier: app
  

image:
  repository: shejulv088/final_config_server
  tag: "4-d4e1e97"

service:
  type: ClusterIP
  port: 8888

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  container:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false  

config: {}
secret: {}

# -------------------------
# Startup Probe  # startupProbe handles startup delay
# -------------------------
startupProbe:
  path: /actuator/health
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 30   # 150 sec startup time

# -------------------------
# Liveness Probe
# -------------------------
livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10   # 🔥 reduce
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 5

# -------------------------
# Readiness Probe
# -------------------------
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 5    # 🔥 reduce
  periodSeconds: 10         # 🔥 faster response
  timeoutSeconds: 2
  failureThreshold: 3

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
