apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-to-mysql
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "mysql-auth-service"

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: "auth-service"